### ISSUE TITLE
Is jQuery supported?

### ISSUE THREAD

**Issue by eboye** [spatie/laravel-mix-purgecss#12]
Hi,

I really like the idea, but I'm not using Vue in projects. I have a lot of javascript with jQuery selectors. So as description states it's for Vue based projects. But maybe it's working with jQuery. So better to ask first 😄

**Comment by sebastiandedeyne** [comment]
Don't know where you got the impression it's for Vue-based projects, it works anywhere! `.vue` is one of the many extensions we're looking for class names in.

Give it a shot, and let me know if something's unclear or not working as expected!
