### ISSUE TITLE
laravel mix purgecss options exclude folder

### ISSUE THREAD

**Issue by danstoian07** [spatie/laravel-mix-purgecss#121]
I want to purge the css from the "frontend" folder, but exclude the "backend" folder.
Is there any option to do this?

I tried adding:
content: [path.join(__dirname, 'resources/views/frontend/**/*.php')],

It doesn't seem to do anything. All the folders are purged.

**Comment by recoverjp** [comment]
@danstoian07 Did you solve it? I also need this.

**Comment by mayanksdudakiya** [comment]
Yes, Please add an option.

Thanks in advance
