### ISSUE TITLE
Question: Is there a way to have a specific css file ignored from the purgeCss process?

### ISSUE THREAD

**Issue by ockam** [spatie/laravel-mix-purgecss#13]
I currently compiling 2 sass files and I want one to completely bypass purgeCss. I have tried the various whitelist options of purgeCss, but in the best case, it works only partially.

Thanks for this great package!

**Comment by sebastiandedeyne** [comment]
I don't think you can ignore a file, but you can do the opposite, declare the only files you cant to purge.

From the purgecss-webpack-plugin documentation:

> You can specify entrypoints to the purgecss-webpack-plugin with the option only:
>
> ```js
> new PurgecssPlugin({
>   paths: glob.sync(`${PATHS.src}/*`),
>   only: ['bundle', 'vendor']
> })
> ```

You can pass any of these options directly to the plugin, so in your mix file it'd look like this:

```js
mix.purgeCss({
  only: ['app']
})
```

Options docs: https://github.com/FullHuman/purgecss-webpack-plugin#options

Hope this helps!

**Comment by ockam** [comment]
Sadly, when I use `only`, mix doesn’t output the other file at all. Looks like the condition is applied to the whole process.

Here’s my config:
```
mix
  .sass("./_src/scss/style.scss", "public_html/css/")
  .sass("./_src/scss/craft-cp.scss", "public_html/css/")
  .options({
    processCssUrls: false,
    postCss: [tailwindcss("./tailwind.js")]
  })
  .purgeCss({
    globs: [
      path.join(__dirname, "_src/**/*.js"),
      path.join(__dirname, "_src/**/*.vue"),
      path.join(__dirname, "craft/templates/**/*.twig")
    ],
    extensions: ["twig"],
    whitelist: ["sup", "sub", "var", "nowrap-ns"],
    only: ['style']
  });
```
I only want `style` to go trough purgeCss.

**Comment by sebastiandedeyne** [comment]
Your entry might be wrong. I think it needs an extension too. Here's a working example Mix config file: https://github.com/spatie/blender/blob/master/webpack.mix.js

The entry can be determined by looking at the left column of Webpack's output.

<img width="628" alt="screen shot 2018-02-02 at 14 12 46" src="https://user-images.githubusercontent.com/1561079/35734972-52484114-0823-11e8-9eea-8dccace36ee2.png">

**Comment by ockam** [comment]
You are right, it needs the extension. Works fine now. Thanks!

`only: ["style.css"]`
