### ISSUE TITLE
Missing readme warning: doesn't work with externally loaded packages

### ISSUE THREAD

**Issue by aTanCS** [spatie/laravel-mix-purgecss#14]
E.g. if you use bootstrap-vue package from CDN, you can't use purgecss, because it doesn't know about selectors used in it and will strip out needed css. I guess it should be mentioned in Readme.

**Comment by sebastiandedeyne** [comment]
This package is a simple wrapper for Purgecss, not Purgecss itself. I don't think we'll be adding a "Purgecss caveats" section to the readme, they already have docs for that.
