### ISSUE TITLE
Doesn't work with Tailwind?

### ISSUE THREAD

**Issue by Sjoerrdd** [spatie/laravel-mix-purgecss#16]
Hello,
This package does not work with TailwindCSS?

My code:
```js

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
     .options({
       processCssUrls: false,
       postCss: [ tailwindcss('./tailwind.js') ],
     })
   .purgeCss();
```

**Comment by sebastiandedeyne** [comment]
That setup looks correct. By default it only purges when building _production_ assets, are you sure you're not in dev mode?

**Comment by cmizzi** [comment]
I doesn't work for me at all with TailwindCSS (in `dev` or `prod` mode)

**Comment by sebastiandedeyne** [comment]
Sorry, but you'll need to share a repository that fails. 

Until now we haven't had any issues with other users. It could be that another dependency broke something, but we'll need to see a live example of that to debug.

**Comment by cmizzi** [comment]
Hum, after some tests, it works with tailwind, but doesn't work with Fontawesome, it loads every icons (even not used)

**Comment by Sjoerrdd** [comment]
When I run it in production, it works.
Bedankt Sebastian
