### ISSUE TITLE
2.0.0 tag not available on NPM

### ISSUE THREAD

**Issue by dwightwatson** [spatie/laravel-mix-purgecss#27]
Forgive me if I'm looking at the wrong thing, but the repo seems to indicate that `2.0.0` has been released - both in the docs but also under the "releases" tab. However, NPM shows that the latest available version is `2.0.0-rc.1` and that's the only available version when I try to upgrade to it.

```
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "laravel-mix-purgecss" that matches "^2.0"
? Please choose a version of "laravel-mix-purgecss" from this list: (Use arrow keys)
❯ 2.0.0-rc.1 
  1.0.5 
  1.0.4 
  1.0.3 
  1.0.3-beta.1 
  1.0.2 
  1.0.1 
  1.0.0 
  0.3.0 
  0.2.0 
  0.1.0 
```

Am I missing something, or has `2.0.0` not been tagged properly yet?

(And thanks, of course, for putting this library together!)

**Comment by sebastiandedeyne** [comment]
Hmm something must've gone wrong with `publish`, it's there now :)
