### ISSUE TITLE
PurgeCSS breaks on BEM like class names

### ISSUE THREAD

**Issue by wiljanslofstra** [spatie/laravel-mix-purgecss#38]
Since version 2.2.2 PurgeCSS breaks my CSS. In projects I frequently use BEM like classnames: 

```html
navigation__item
```

Before 2.2.2 everything worked correctly, but in 2.2.2 this broke. This issue is probably in the Regex change:

```
[A-z0-9-:/]+
```
Test case: [regexr.com/3tbmg](https://regexr.com/3tbmg)

matched my class correctly, but this one doesn't:

```
[a-zA-Z0-9-:/]+
```
Test case: [regexr.com/3tbmj](https://regexr.com/3tbmj)

Probably because `A-z` also matches underscores?

**Comment by cjmaxik** [comment]
https://github.com/spatie/laravel-mix-purgecss/pull/37

**Comment by freekmurze** [comment]
We'll continue this in #37
