### ISSUE TITLE
globs cant be fully replaced

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-mix-purgecss#41]
according to 
https://github.com/spatie/laravel-mix-purgecss/blame/master/README.md#L92-L93

adding 
```js
globs: [
   path.join(__dirname, 'node_modules/simplemde/**/*.js'),
],
```
should replace the package defaults, but because of 

https://github.com/spatie/laravel-mix-purgecss/blob/c48b79335d1654f9f0d397c88ae602cf53fa14dc/src/index.js#L32-L39

this is not possible and you are basically adding an extra entry point to be scanned.

also https://github.com/spatie/laravel-mix-purgecss#usage-outside-of-laravel is not true because if `root/app/` is not found you will get an error.

to test
- add the `globs` option 
- add `console.log(JSON.stringify(globs, null, 1));` to https://github.com/spatie/laravel-mix-purgecss/blob/master/src/createPurgeCssPlugin.js
- run `npm run dev/watch` and check the console

btw globs extension could be omitted https://github.com/FullHuman/purgecss-webpack-plugin/blame/master/README.md#L68 as purgecss will use the extensions option to fill it.

**Comment by sebastiandedeyne** [comment]
Globs aren't meant to ever fully replaced, this is mentioned in the readme:

> If you need to fully replace the globs, use the underlying paths option instead.

I do agree that the hard coded `app` should go. I think this can be moved to `folders`, doesn't really matter if `app` gets scanned for more extensions than PHP.

**Comment by ctf0** [comment]
> If you need to fully replace the globs

this part should be changed because you cant fully replace it, still i can make a PR with a check for globs, if empty then use
```js
this.options.globs.push( 
     ...flatMap(this.options.folders, folder => { 
         return this.options.extensions.map(extension => 
             rootPath(`${folder}/**/*.${extension}`) 
         ); 
     }) 
 ); 
```

**Comment by sebastiandedeyne** [comment]
`globs` is **not** a Purgecss option, it's custom made for this wrapper. `paths` is the actual configuration property. If you specify a custom `paths` option, `globs` will be completely ignored.

https://github.com/FullHuman/purgecss-webpack-plugin#paths

`mix.purgeCss({ paths: ... })`

**Comment by ctf0** [comment]
oh okay, so which PR do u prefer

- for the docs, update with `paths` instead of `globs` to clear the confusion
https://github.com/spatie/laravel-mix-purgecss/blame/master/README.md#L94-L96

- or add a condition for globs to replace it and use the current as a fallback when empty

?

**Comment by sebastiandedeyne** [comment]
Feel free to send a PR  that improves the docs regarding `paths` vs. `globs`. However, we're going to keep `globs` as the recommended configuration, and not going to change it's behavior. For most people, `globs` is more than enough and is easier to configure.
