### ISSUE TITLE
this.options.globs.push is not a function

### ISSUE THREAD

**Issue by poldixd** [spatie/laravel-mix-purgecss#66]
For those who get the error `this.options.globs.push is not a function`: If you use the _Example custom configuration_ `globs` must be an array and not a function. There is an mistake in the `README.md`:

change this:
```
        globs: () => [
            path.join(__dirname, 'node_modules/simplemde/**/*.js'),
        ],
```
to this:

```
        globs:  [
            path.join(__dirname, 'node_modules/simplemde/**/*.js'),
        ],
```

Pull Request #60 was created but not merged.

**Comment by sebastiandedeyne** [comment]
It's not a mistake, this has changed in Purgecss if that's the case. Providing a function for globs used to re-evaluate the glob when watching with Webpack, not sure how to do this now but it's rarely necessary. I'll merge your PR for the readme change, thanks!

**Comment by poldixd** [comment]
Thanks Sebastian!
