### ISSUE TITLE
PurgeCss on mutiple css files

### ISSUE THREAD

**Issue by ebrahimirad** [spatie/laravel-mix-purgecss#79]
Hi dear friends,
I have multiple SCSS files for different pages but final PurgeCss command apply on all css files. Please help me, thanks

`mix.sass('resources/assets/sass/app.scss', 'public/build/css').options({ processCssUrls: false }).purgeCss({
    enabled: true,
    whitelistPatterns: whitelistPatterns
}).version();

mix.sass('resources/assets/sass/app-home.scss', 'public/build/css').options({ processCssUrls: false }).purgeCss({
    enabled: true,
    paths: () => glob.sync([
        path.join(__dirname, 'resources/views/layouts/app.blade.php'),
        path.join(__dirname, 'resources/views/layouts/flushMessage.blade.php'),
        path.join(__dirname, 'resources/views/layouts/appHeader.blade.php'),
        path.join(__dirname, 'resources/views/layouts/appFooter.blade.php'),
        path.join(__dirname, 'resources/views/layouts/callNumber.blade.php'),
        path.join(__dirname, 'resources/views/home.blade.php'),
        path.join(__dirname, 'resources/views/home/*.blade.php'),
    ]),
    whitelistPatterns: whitelistPatterns
}).version();

mix.sass('resources/assets/sass/app-teacher-list.scss', 'public/build/css').options({ processCssUrls: false }).purgeCss({
    enabled: true,
    paths: () => glob.sync([
        path.join(__dirname, 'resources/views/layouts/app.blade.php'),
        path.join(__dirname, 'resources/views/layouts/flushMessage.blade.php'),
        path.join(__dirname, 'resources/views/layouts/appHeader.blade.php'),
        path.join(__dirname, 'resources/views/layouts/appFooter.blade.php'),
        path.join(__dirname, 'resources/views/layouts/callNumber.blade.php'),
        path.join(__dirname, 'resources/views/teacherList.blade.php'),
    ]),
    whitelistPatterns: whitelistPatterns
}).version();`

**Comment by ivandokov** [comment]
This is indeed an issue. The most common use case is admin panel + public facing apps in a single Laravel app. They could have completely separate assets.

**Comment by divdax** [comment]
Would love to see this too. i use separate css for admin and frontend.

**Comment by ivandokov** [comment]
I think the case is still relevant and it deserves attention.

**Comment by rdpascua** [comment]
I'm having the same issue

**Comment by danielbachhuber** [comment]
This approach did the trick for me: https://github.com/spatie/laravel-mix-purgecss/issues/73#issuecomment-523490163
