### ISSUE TITLE
Update PurgeCSS to version 2

### ISSUE THREAD

**Issue by ben-rogerson** [spatie/laravel-mix-purgecss#81]
Hey team Spatie
Now that [PurgeCSS v2](https://github.com/FullHuman/purgecss/tree/master/packages/purgecss-webpack-plugin) has been released it would be great if this plugin could be updated to match.
Cheers!

**Comment by sebastiandedeyne** [comment]
I'm planning to work on a new major version of this plugin this week. To be continued!

**Comment by sebastiandedeyne** [comment]
I'm planning to rework the plugin to use the postcss plugin for Purgecss (atm it uses the Webpack plugin). 

The postcss plugin doesn't have v2 support yet, but since it's a first party package I don't think it will take long until it does. When that package gets tagged, I'm going to get the next major version of this package going.

**Comment by sebastiandedeyne** [comment]
I just tagged `v5.0.0-rc.2` which uses PurgeCSS v2. 

To whoever's following this issue, I'd love to hear if it works as intended in your apps!

**Comment by mvdnbrk** [comment]
@sebastiandedeyne just updated to `rc.2`. No problems at all, as far as I can see 😄

**Comment by slaFFik** [comment]
@sebastiandedeyne Got a problem: dropdowns in Bootstrap stopped working with this in my mix file:
```
mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
    .purgeCss({
       enabled: true,
   });
```

I have `"laravel-mix-purgecss": "^5.0.0-rc.3",` installed.

Related HTML from my view:
```
<li class="nav-item dropdown">
    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        {{ Auth::user()->name }} <span class="caret"></span>
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        @if (Auth::user()->hasVerifiedEmail())
            <a class="dropdown-item" href="{{ route('account') }}">
                {{ __('Account') }}
            </a>
        @endif

        <a class="dropdown-item" href="{{ route('logout') }}"
           onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </div>
</li>
```

Dropdown becomes unclickable and doesn't show. Removing `{enabled: true}` makes local css file big again (all bootstrap files), and dropdown starts working.

**Comment by sebastiandedeyne** [comment]
Could you run `npm update` or `yarn upgrade` and see if it helps? (the underlying `postcss-purgecss-laravel` dependency should be `0.1.2`)

If not, what does your `webpack.mix.js` file look like?

**Comment by sebastiandedeyne** [comment]
This is released in v5!
