### ISSUE TITLE
Whitelist classes

### ISSUE THREAD

**Issue by RahulDey12** [spatie/laravel-mix-purgecss#83]
how can I whitelist this class  `:not(.layout-fixed) .main-sidebar`

**Comment by sebastiandedeyne** [comment]
For a complex selector like this, you're probably best off with inline Purgecss ignore comments.

```css
/* purgecss start ignore */
:not(.layout-fixed) .main-sidebar {
  /* ... */
}
/* purgecss end ignore */

**Comment by RahulDey12** [comment]
But it is coming from vendor stylesheet

**Comment by sebastiandedeyne** [comment]
In that case, you'll need to add a whitelist pattern. Check out Purgecss' whitelisting docs.

https://purgecss.com/whitelisting.html#specific-selectors

```js
mix.purgeCss({
  whitelist: ['main-sidebar']
})
```

**Comment by saraElsanan** [comment]
i tried this but it doesn't work for ... the weird thing that it select some classes and ignore others , 
for example .iti-flag.eg it ignores it , but .iti-flag.ca it magically appears correct , which doesn't make any sense , I also tried to use /iti-flag*/ , /iti-flag$/ , /$iti-flag/ and still got this weird issue .
Any help please  

> In that case, you'll need to add a whitelist pattern. Check out Purgecss' whitelisting docs.
> 
> https://purgecss.com/whitelisting.html#specific-selectors
> 
> ```js
> mix.purgeCss({
>   whitelist: ['main-sidebar']
> })
> ```

**Comment by saraElsanan** [comment]
> For a complex selector like this, you're probably best off with inline Purgecss ignore comments.
> 
> ```css
> /* purgecss start ignore */
> :not(.layout-fixed) .main-sidebar {
>   /* ... */
> }
> /* purgecss end ignore */
> ```

this solution also doesn't work with @import '~vue-tel-input/dist/vue-tel-input.css';  :(
Any help Please

**Comment by sebastiandedeyne** [comment]
Sorry, this repo is just a wrapper for Purgecss. If you're having issues with Purgecss usage, you'll need to open an issue at https://github.com/FullHuman/purgecss.

**Comment by saraElsanan** [comment]
> Sorry, this repo is just a wrapper for Purgecss. If you're having issues with Purgecss usage, you'll need to open an issue at https://github.com/FullHuman/purgecss.

okay thanks
