### ISSUE TITLE
Laravel blade component classes not being discovered

### ISSUE THREAD

**Issue by booni3** [spatie/laravel-mix-purgecss#86]
Commenting classes inside the blade.php file works as expected, but should we expect css classes defined within the PHP class of to be found too?

This works...
```blade
{{-- bg-gray-100 text-gray-800' --}}
<span {{ $attributes->merge() }}>
  {{ $slot }}
</span>
```

This does not work...
```php
public function __construct($colour = 'gray')
{
    if ($colour == 'gray') {
        $this->colour = 'bg-gray-100 text-gray-800';
    }
}
```
```blade
<span {{ $attributes->merge(['class' => $colour]) }}>
  {{ $slot }}
</span>
```

**Comment by sebastiandedeyne** [comment]
This package scans the following (and more) for content:

- `app/**/*.php`
- `resources/**/*.php`

If your Blade component files are stored in either of those, it should work. Where are your component classes?
