### ISSUE TITLE
Requiring the module in the Mix configuration

### ISSUE THREAD

**Issue by alexpgates** [spatie/laravel-mix-purgecss#9]
Quick question regarding requiring the module in the Mix configuration.

The readme shows:

`require('laravel-mix-purgecss')();`

I was running into issues until I removed the the trailing `()` 

Am I missing something, or is that just a typo? Things _seem_ to be working just fine now (my file is now 66% smaller, and everything looks great!) - but I wanted to double check, just in case.
Apologies for my lack of experience with laravel mix / webpack. And, of course, thank you for all you do for the community. :)

**Comment by mikerockett** [comment]
Same thing here – I think the readme just needs to be updated…

**Comment by the94air** [comment]
Me too.

**Comment by sebastiandedeyne** [comment]
Yeah, gotta drop the brackets. I accidentally reverted some readme changes a few versions ago, sorry for the confusion!

**Comment by the94air** [comment]
No problem :smile:. I tried it out and it is for sure a Zero-config package. :ok_hand:
