### ISSUE TITLE
Is necessary this package with Tailwind 2.0

### ISSUE THREAD

**Issue by andresgutgon** [spatie/laravel-mix-purgecss#92]
# What?
Hi, first of all thanks for your work. Without PurgeCSS Tailwind lost its value. So thanks for allowing to use it with Laravel Mix :)

Now I wanted to ask if this package is necessary with new Tailwind. I just tryed their config without this package and looks it is working fine:

`tailwind.config.js` 👇 
![image](https://user-images.githubusercontent.com/49499/101944608-48d2e200-3bed-11eb-8076-8ecc8eee9fea.png)

Am I missing something?

**Comment by sebastiandedeyne** [comment]
Nope, this package isn't necessary anymore for Tailwind since it has purging built in :)

**Comment by andresgutgon** [comment]
Thanks!
